### ISSUE TITLE
after installation, get this error on Mac

### ISSUE THREAD

**Issue by zhangjiannan** [lhartikk/naivechain#1]
naivechain/main.js:11
class Block {
^^^^^
SyntaxError: Unexpected reserved word
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

npm ERR! naivechain@1.0.0 start: `node main.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the naivechain@1.0.0 start script.
npm ERR! This is most likely a problem with the naivechain package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node main.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls naivechain
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 15.6.0
npm ERR! command "node" "/usr/local/bin/npm" "start"
npm ERR! cwd /naivechain
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.9
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!    naivechain/npm-debug.log
npm ERR! not ok code 0

**Comment by pannous** [comment]
`node -v v0.10.28 ?`
add 4 to that

**Comment by TSavo** [comment]
Yeah, upgrade your node or use babel.

**Comment by gentleKun** [comment]
Your node version is too low.
